// Generated by CoffeeScript 1.3.1
(function() {
  var Context2D;

  Context2D = (function() {

    Context2D.name = 'Context2D';

    function Context2D(width, height) {
      var canvas, proto;
      canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      document.body.insertBefore(canvas, document.body.firstChild);
      proto = this.__proto__;
      this.__proto__ = this.prototype = canvas.getContext('2d');
      OBJ_X(this, proto);
      this.f = Math.floor;
    }

    Context2D.prototype.draw_circle = function(x, y, r) {
      this.beginPath();
      this.arc(x, y, r, 0, Math.PI * 2, true);
      this.fill();
      return this.stroke();
    };

    Context2D.prototype.draw_line = function(a, b) {
      this.beginPath();
      this.moveTo(a.x, a.y);
      this.lineTo(b.x, b.y);
      return this.stroke();
    };

    Context2D.prototype.draw = function(x) {
      if (x.draw) {
        return x.draw(this);
      }
      throw new Error("can't Context2D.draw(x)");
    };

    Context2D.prototype.arc = function(x, y, r, s, e, c) {
      return this.prototype.arc(this.f(x), this.f(y), this.f(r), s, e, c);
    };

    Context2D.prototype.moveTo = function(x, y) {
      return this.prototype.moveTo(this.f(x), this.f(y));
    };

    Context2D.prototype.lineTo = function(x, y) {
      return this.prototype.lineTo(this.f(x), this.f(y));
    };

    Context2D.prototype.translate = function(x, y) {
      return this.prototype.translate(this.f(x), this.f(y));
    };

    return Context2D;

  })();

  OBJ_X(window, {
    Context2D: Context2D
  });

}).call(this);
