// Generated by CoffeeScript 1.3.1
(function() {
  var Layer, foo,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  foo = [];

  Layer = (function() {

    Layer.name = 'Layer';

    function Layer(_arg) {
      this.size = (_arg != null ? _arg : {}).size;
      this.draw = __bind(this.draw, this);

      this.update = __bind(this.update, this);

      this.set_ground = __bind(this.set_ground, this);

      this.$ = {
        objs: new Objs
      };
      if (this.size == null) {
        this.size = v(100, 100);
      }
      this.ground = null;
      this.ctx = new Context2D(this.size.x, this.size.y);
    }

    Layer.prototype.set_ground = function(ground) {
      if (this.ground) {
        this.$.objs.rem(this.ground);
      }
      if (this.ground = ground) {
        return this.$.objs.add(this.ground);
      }
    };

    Layer.prototype.update = function(dt) {
      var id, x, _ref;
      _ref = this.$.objs.all;
      for (id in _ref) {
        x = _ref[id];
        x.update(dt);
      }
      return;
    };

    Layer.prototype.draw = function() {
      var ctx, id, x, _ref, _results;
      ctx = this.ctx;
      _ref = this.$.objs.all;
      _results = [];
      for (id in _ref) {
        x = _ref[id];
        _results.push(ctx.draw(x));
      }
      return _results;
    };

    return Layer;

  })();

  window.Layer = Layer;

}).call(this);
