// Generated by CoffeeScript 1.3.1
(function() {
  var Loop,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Loop = (function() {

    Loop.name = 'Loop';

    function Loop(update) {
      this.update = update;
      this.step = __bind(this.step, this);

      this.stop = __bind(this.stop, this);

      this.looping = __bind(this.looping, this);

      this.start = __bind(this.start, this);

      this.running = false;
      this.last_step = null;
    }

    Loop.prototype.start = function() {
      if (this.running) {
        return;
      }
      this.running = true;
      this.last_step = Date.now();
      return this.looping();
    };

    Loop.prototype.looping = function() {
      if (!this.running) {
        return;
      }
      this.step();
      return delay(this.looping);
    };

    Loop.prototype.stop = function() {
      return this.running = false;
    };

    Loop.prototype.step = function() {
      var dt, now;
      now = Date.now();
      dt = (now - this.last_step) / 1000;
      this.last_step = now;
      return this.update(dt);
    };

    return Loop;

  })();

  window.Loop = Loop;

}).call(this);
