// Generated by CoffeeScript 1.3.1
(function() {
  var Objs,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  Objs = (function() {

    Objs.name = 'Objs';

    function Objs(_arg) {
      this.all = (_arg != null ? _arg : {}).all;
      this.rem = __bind(this.rem, this);

      this.add = __bind(this.add, this);

      if (this.all == null) {
        this.all = {};
      }
    }

    Objs.prototype.add = function() {
      var o, os, _i, _len, _results;
      os = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _results = [];
      for (_i = 0, _len = os.length; _i < _len; _i++) {
        o = os[_i];
        _results.push(this.all[get_id(o)] = o);
      }
      return _results;
    };

    Objs.prototype.rem = function() {
      var o, os, _i, _len, _results;
      os = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _results = [];
      for (_i = 0, _len = os.length; _i < _len; _i++) {
        o = os[_i];
        _results.push(delete this.all[get_id(o)]);
      }
      return _results;
    };

    return Objs;

  })();

  window.Objs = Objs;

}).call(this);
