// Generated by CoffeeScript 1.3.1
(function() {
  var Tree,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Tree = (function() {
    var ctx, img;

    Tree.name = 'Tree';

    function Tree(_arg) {
      var layer;
      layer = _arg.layer;
      this.update = __bind(this.update, this);

      this.draw = __bind(this.draw, this);

      this.update_y = __bind(this.update_y, this);

      this.set_p = __bind(this.set_p, this);

      this.set_ground = __bind(this.set_ground, this);

      this.set_layer = __bind(this.set_layer, this);

      this.p = v(0, 0);
      this.ground = null;
      this.layer = null;
      this.set_layer(layer);
    }

    Tree.prototype.set_layer = function(layer) {
      if (this.layer) {
        this.layer.$.objs.rem(this);
      }
      this.layer = layer;
      if (this.layer) {
        this.layer.$.objs.add(this);
        this.set_ground(this.layer.ground);
      }
      return this.layer;
    };

    Tree.prototype.set_ground = function(ground) {
      this.ground = ground;
      return this.update_y();
    };

    Tree.prototype.set_p = function(p) {
      OBJ_X(this.p, p);
      return this.update_y();
    };

    Tree.prototype.update_y = function() {
      if (this.ground) {
        return this.p.y = this.ground.top(this.p.x);
      }
    };

    Tree.prototype.draw = function(ctx) {
      return ctx.drawImage(this.img, this.p.x - 20, this.p.y - 50);
    };

    Tree.prototype.draw_tree = function(ctx) {
      ctx.beginPath();
      ctx.moveTo(20, 0);
      ctx.lineTo(0, 35);
      ctx.lineTo(40, 35);
      ctx.closePath();
      ctx.fill();
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(20, 50);
      ctx.lineTo(20, 35);
      return ctx.stroke();
    };

    Tree.prototype.update = function(dt) {
      var _ref;
      if ((_ref = this.ground) != null ? _ref.changed : void 0) {
        return this.update_y();
      }
    };

    Tree.prototype.img = img = document.createElement('canvas');

    img.width = 40;

    img.height = 50;

    ctx = img.getContext('2d');

    Tree.prototype.draw_tree(ctx);

    return Tree;

  })();

  OBJ_X(window, {
    Tree: Tree
  });

}).call(this);
